# appveyor.yml for building a Windows driver with MSVC 2015 and WDK 10.0.14393
version: 1.0.{build}
image: Visual Studio 2015

environment:
  WDKPath: "C:\\Program Files (x86)\\Windows Kits\\10"
  Platform: x64

install:
  # Install Visual Studio 2015 WDK components if needed
  - ps: |
      if (!(Test-Path "${env:WDKPath}\Include\10.0.14393.0")) {
        Write-Host "WDK not found. Please ensure WDK 10.0.14393 is installed."
        Exit 1
      }

build_script:
  - ps: |
      # Set up the WDK environment
      $env:WDK_INC = Join-Path $env:WDKPath "Include\10.0.14393.0"
      $env:WDK_LIB = Join-Path $env:WDKPath "Lib\10.0.14393.0"
      
      # Verify the WDK installation
      if (!(Test-Path $env:WDK_INC) -or !(Test-Path $env:WDK_LIB)) {
        throw "WDK 10.0.14393 not found!"
      }
      
  - cmd: |
      # Use MSBuild to compile the driver
      MSBuild.exe SOURCES /p:Configuration=Release;Platform=%Platform%

artifacts:
  - path: bin\Release\$(Platform)\*.sys
    name: Driver Files
    type: File
