version: 1.0.{build}

# Environment configuration
environment:
  matrix:
    - platform: x64
    - platform: x86
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  WDK_SETUP_URL: "https://go.microsoft.com/fwlink/?linkid=2128854"

# Install dependencies
install:
  - powershell -Command "Write-Output 'Downloading and installing the latest WDK from Microsoft...'"
  - powershell -Command "Invoke-WebRequest -Uri $env:WDK_SETUP_URL -OutFile wdksetup.exe"
  - powershell -Command "Start-Process -FilePath .\wdksetup.exe -ArgumentList '/quiet' -Wait"
  - powershell -Command "Write-Output 'WDK installation complete.'"
  
  # Verifying WDK installation
  - powershell -Command "
      Write-Output 'Verifying WDK installation...'
      if (-Not (Test-Path 'C:\Program Files (x86)\Windows Kits\10')) {
          throw 'WDK installation failed!'
      } else {
          Write-Output 'WDK installed successfully.'
      }
  "

# Build configuration
build_script:
  - powershell -Command "Write-Output 'Starting build for $env:platform...'"
  - msbuild /p:Configuration=Release /p:Platform=$env:platform driver\DriverProject.sln
