
version: 1.0.{build}

environment:
  matrix:
    - platform: x64
    - platform: x86
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)

configuration:
  - Release
  - Debug

branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  # Download and install Windows Driver Kit (WDK)
  - ps: Install-Product $env:platform
  - appveyor DownloadFile https://go.microsoft.com/fwlink/?linkid=2085767 -FileName wdksetup.exe
  - wdksetup.exe /quiet /norestart
  - ps: Start-Sleep -s 15

before_build:
  - cd driver
  - mkdir build
  - cd build

build:
  verbosity: detailed

build_script:
  - msbuild ..\*.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% /p:UseEnv=true

after_build:
  - mkdir %artifactName%
  - xcopy /E /I ..\%CONFIGURATION%\* %artifactName%\

artifacts:
  - path: driver\build\%artifactName%
    name: Driver_%PLATFORM%
    type: zip
