
  
# Environment configuration
environment:
  matrix:
    - platform: x64
    - platform: x86
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  WDK_SETUP_URL: "https://go.microsoft.com/fwlink/?linkid=2128854"

# Install dependencies
install:
  - powershell: |
      Write-Output 'Downloading and installing the latest WDK from Microsoft...'
      try {
          Invoke-WebRequest -Uri $env:WDK_SETUP_URL -OutFile wdksetup.exe -ErrorAction Stop
          Start-Process -FilePath .\wdksetup.exe -ArgumentList '/quiet' -Wait
          Write-Output 'WDK installation complete.'
      }
      catch {
          Write-Error "Failed to download or install WDK: $_"
          exit 1
      }
  
  - powershell: |
      Write-Output 'Verifying WDK installation...'
      if (-Not (Test-Path 'C:\Program Files (x86)\Windows Kits\10')) {
          Write-Error 'WDK installation failed - Windows Kits directory not found!'
          exit 1
      }
      Write-Output 'WDK verified successfully.'

# Build configuration
build_script:
  - ps: |
      # Set output directory relative to build folder
      $buildDir = $env:APPVEYOR_BUILD_FOLDER
      $outputDir = Join-Path $buildDir "bin\$env:platform\Release"
      Write-Output "Build directory: $buildDir"
      Write-Output "Output directory: $outputDir"

      # Create output directory
      New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
      
      # Build the solution
      $solutionPath = "driver\DriverProject.sln"
      Write-Output "Building solution: $solutionPath"
      
      $msbuildPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
      if (-not (Test-Path $msbuildPath)) {
          $msbuildPath = "msbuild"
      }

      & $msbuildPath $solutionPath `/p:Configuration=Release `/p:Platform=$env:platform `/p:OutDir=$outputDir `/verbosity:normal

      if ($LastExitCode -ne 0) {
          Write-Error "Build failed with exit code $LastExitCode"
          throw "Build failed"
      }

      # List files in output directory
      Write-Output "`nFiles in output directory:"
      Get-ChildItem -Path $outputDir -Recurse | ForEach-Object {
          Write-Output $_.FullName
      }

after_build:
  - ps: |
      # Package artifacts
      $artifactDir = Join-Path $env:APPVEYOR_BUILD_FOLDER "artifacts\$env:platform"
      New-Item -ItemType Directory -Force -Path $artifactDir | Out-Null
      
      # Copy build outputs to artifact directory
      Copy-Item -Path "$outputDir\*" -Destination $artifactDir -Recurse -Force
      
      Write-Output "`nContents of artifact directory:"
      Get-ChildItem -Path $artifactDir -Recurse | ForEach-Object {
          Write-Output $_.FullName
      }

# Artifacts configuration
artifacts:
  - path: artifacts\$(platform)\*
    name: Driver_$(platform)
    type: zip

# On build success
on_success:
  - ps: Write-Output "Build completed successfully. Artifacts should be available."
   
