# AppVeyor Configuration File
version: 1.0.{build}

environment:
  platform: x64
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  WDK_VERSION: 10.0.22621.0

install:
  - ps: |
      Write-Output "Installing WDK version $env:WDK_VERSION..."
      choco install windows-driver-kit --version=10.0.22621.0

before_build:
  - cmd: set

build_script:
  - ps: |
      Write-Output "Building for $env:platform..."
      msbuild /p:Configuration=Release /p:Platform=$env:platform DriverProject.sln

   
