
# AppVeyor configuration for compiling a Windows driver

version: "{build}"
image: Visual Studio 2019

# Environment variables
environment:
  platform: x64
  configuration: Release
  WDK_PATH: C:\Program Files (x86)\Windows Kits\10

build_script:
  - ps: |
      # Ensure WDK and SDK environment is set up
      Write-Output "Setting up WDK and SDK environment..."
      $wdkEnv = "$env:WDK_PATH\bin\10.0.17763.0\x64\setenv.bat"
      if (Test-Path $wdkEnv) {
          cmd /c "$wdkEnv" &&
          Write-Output "WDK environment set up successfully."
      } else {
          Write-Output "Failed to locate WDK environment setup script."
          exit 1
      }

      # Build the driver project
      Write-Output "Building the driver..."
      msbuild hdsnspoofer.sln /p:Configuration=$env:configuration /p:Platform=$env:platform

artifacts:
  - path: bin\x64\Release\*.sys
    name: Driver Binary
    type: file
  - path: bin\x64\Release\*.inf
    name: Driver INF
    type: file
